#ifndef SCENE_DEFINES
#define SCENE_DEFINES

#define BOUNDS_HALF_WIDTH 10
#define BOUNDS_HALF_HEIGHT 8

#define BOTTOM_LEFT_PLATFORM_X -5
#define BOTTOM_LEFT_PLATFORM_Y -6
#define PLATFORM_VERTICAL_SPACE 2
#define BOTTOM_PLATFORM_WIDTH 2
#define PLATFORM_WIDTH_DROP 0.5
#define PLATFORM_DIM 0.1
#define PLATFORM_COUNT 3

#define PLAYER_WIDTH 0.5
#define PLAYER_HEIGHT 1.5

#define HELPER_RADIUS 0.4

#define SNOWFLAKE_RADIUS 0.25

#define SNOWBALL_RADIUS 0.2

#define FIREBALL_RADIUS 0.45

#define SNOWMAN_BOT_RADIUS 2.0
#define SNOWMAN_MID_RADIUS 1.5
#define SNOWMAN_TOP_RADIUS 1.1
#define SNOWMAN_X 0.0
#define SNOWMAN_BOT_Y -7.4
#define SNOWMAN_MID_Y -4.65
#define SNOWMAN_TOP_Y -2.5
#define SNOWMAN_Z -7.0

#define MESH_TYPE_PLAYER 0
#define MESH_TYPE_HELPER 1
#define MESH_TYPE_SNOW_FLAKE 2
#define MESH_TYPE_SNOW_BALL 3
#define MESH_TYPE_SNOW_MAN 4
#define MESH_TYPE_STATIC_PLATFORMS 5
#define MESH_TYPE_WORLD_BOUNDS 6
#define MESH_TYPE_FIRE_BALL 7
#define MESH_TYPE_GROUND_PLANE 8
#define MESH_TYPE_TREE 9
#define MESH_TYPE_COUNT 10

#define MAX_SCENE_ENTRIES 256
#define BLOOM_BLUR_PASSES 5

#endif //#ifndef STATIC_SCENE_DEFINES
