#ifndef SCENE_DEFINES
#define SCENE_DEFINES

#define BOUNDS_HALF_WIDTH 10
#define BOUNDS_HALF_HEIGHT 8

#define BOTTOM_LEFT_PLATFORM_X -5
#define BOTTOM_LEFT_PLATFORM_Y -6
#define PLATFORM_VERTICAL_SPACE 2
#define BOTTOM_PLATFORM_WIDTH 2
#define PLATFORM_WIDTH_DROP 0.5
#define PLATFORM_DIM 0.1
#define PLATFORM_COUNT 3

#define PLAYER_WIDTH 0.5
#define PLAYER_HEIGHT 1.5

#define HELPER_RADIUS 0.5

#define MAX_SCENE_ENTRIES 512

#endif //#ifndef STATIC_SCENE_DEFINES
