#pragma once

// Generated by WAVToC. Do not modify.

extern const unsigned fire_channelCount;
extern const unsigned fire_sampleRate;
extern const unsigned fire_sampleCount;
extern const unsigned fire_bitDepth;
extern const void * const fire_pcmData;
