#pragma once

// Generated by WAVToC. Do not modify.

extern const unsigned footsteps_channelCount;
extern const unsigned footsteps_sampleRate;
extern const unsigned footsteps_sampleCount;
extern const unsigned footsteps_bitDepth;
extern const void * const footsteps_pcmData;
