#pragma once

// Generated by WAVToC. Do not modify.

extern const unsigned hooray_channelCount;
extern const unsigned hooray_sampleRate;
extern const unsigned hooray_sampleCount;
extern const unsigned hooray_bitDepth;
extern const void * const hooray_pcmData;
