#pragma once

// Generated by WAVToC. Do not modify.

extern const unsigned sizzle_channelCount;
extern const unsigned sizzle_sampleRate;
extern const unsigned sizzle_sampleCount;
extern const unsigned sizzle_bitDepth;
extern const void * const sizzle_pcmData;
