#pragma once

// Generated by WAVToC. Do not modify.

extern const unsigned snowman_channelCount;
extern const unsigned snowman_sampleRate;
extern const unsigned snowman_sampleCount;
extern const unsigned snowman_bitDepth;
extern const void * const snowman_pcmData;
