#pragma once

// Generated by WAVToC. Do not modify.

extern const unsigned throw_channelCount;
extern const unsigned throw_sampleRate;
extern const unsigned throw_sampleCount;
extern const unsigned throw_bitDepth;
extern const void * const throw_pcmData;
