#pragma once

// Generated by WAVToC. Do not modify.

extern const unsigned ting_channelCount;
extern const unsigned ting_sampleRate;
extern const unsigned ting_sampleCount;
extern const unsigned ting_bitDepth;
extern const void * const ting_pcmData;
