// Generated by GLSLToC. Do no modify.

#include "Shaders.h"
#include "blur.frag.cpp"
#include "downsample.frag.cpp"
#include "fullscreen_quad.vert.cpp"
#include "output.frag.cpp"
#include "scene.frag.cpp"

extern "C" const unsigned shader_count = 5;
extern "C" const ShaderModule * const shaders[] = {
	&blur_frag_shader,
	&downsample_frag_shader,
	&fullscreen_quad_vert_shader,
	&output_frag_shader,
	&scene_frag_shader,
	nullptr
};
