// Generated by GLSLToC. Do no modify.

#pragma once

struct ShaderModule;

#ifdef EXPORT
# error "'EXPORT' already defined."
#endif //#ifdef EXPORT

#if BUILD_DLL
# define EXPORT __declspec(dllexport)
#elif USE_DLL //#if BUILD_DLL
# define EXPORT __declspec(dllimport)
#else //#elif USE_DLL //#if BUILD_DLL
# define EXPORT
#endif //#else //#elif USE_DLL //#if BUILD_DLL

extern "C" EXPORT const unsigned shader_count;
extern "C" EXPORT const ShaderModule * const shaders[];

#undef EXPORT
